FROM postgis/postgis:17-3.5

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    postgresql-server-dev-17 \
    curl \
    gosu \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/citusdata/pg_cron.git \
    && cd pg_cron \
    && make && make install

RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample \
    && echo "cron.database_name = 'osm_db'" >> /usr/share/postgresql/postgresql.conf.sample

RUN apt-get remove -y build-essential git postgresql-server-dev-17 curl \
    && apt-get autoremove -y \
    && rm -rf /pg_cron
