services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    volumes:
      - ${PG_DATA_HOST_PATH}:/var/lib/postgresql/data
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5

  api:
    build: .
    command: uvicorn osm_meet_your_mappers.api:app --host 0.0.0.0 --workers 4 --proxy-headers --forwarded-allow-ips "*"
    volumes:
      - .:/app
      - ./osm_meet_your_mappers/static:/app/osm_meet_your_mappers/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

  backfill:
    build: .
    working_dir: /app
    command: python -m scripts.backfill
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
