volumes:
  osm_archives:
    driver: local

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    volumes:
      - ${PG_DATA_HOST_PATH}:/var/lib/postgresql/data
      - ./scripts/setup_db.sql:/docker-entrypoint-initdb.d/setup_db.sql
    ports:
      - "5432:5432"
    env_file: .env
    command: ["postgres", "-c", "app.retention_period=${RETENTION_PERIOD}"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
    profiles:
      - initialization
      - production

  api:
    build:
      context: .
      target: api
    volumes:
      - .:/app
      - ./osm_meet_your_mappers/static:/app/osm_meet_your_mappers/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - PYTHONPATH=/app
    profiles:
      - production

  backfill:
    build:
      context: .
      target: backfill
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - PYTHONPATH=/app
    profiles:
      - production

  load_admin_boundaries:
    build:
      context: .
      target: load_admin_boundaries
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    profiles:
      - initialization

  archive_loader:
    build:
      context: .
      target: archive_loader
    working_dir: /app
    volumes:
      - .:/app
      - ${LOADER_CHANGESET_FILE}:/archives/changesets.osm.bz2
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - LOADER_CHANGESET_FILE=/archives/changesets.osm.bz2
    restart: "no"
    profiles:
      - initialization
