"""initial setup

Revision ID: 4e2c1dbd8817
Revises: 
Create Date: 2025-02-11 09:47:17.094131

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision = '4e2c1dbd8817'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('changesets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('num_changes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('min_lon', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.Column('max_lon', sa.Float(), nullable=True),
    sa.Column('bbox', Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_changesets_bbox', 'changesets', ['min_lon', 'max_lon', 'min_lat', 'max_lat'], unique=False)
    op.create_geospatial_index('idx_changesets_bbox_geom', 'changesets', ['bbox'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_changesets_comments_count', 'changesets', ['comments_count'], unique=False)
    op.create_index('idx_changesets_created_at', 'changesets', ['created_at'], unique=False)
    op.create_index('idx_changesets_num_changes', 'changesets', ['num_changes'], unique=False)
    op.create_index('idx_changesets_user', 'changesets', ['user'], unique=False)
    op.create_index('idx_changesets_user_created_at', 'changesets', ['user', 'created_at'], unique=False)
    op.create_table('metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('changeset_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('changeset_id', sa.BigInteger(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changeset_id'], ['changesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changeset_comments_changeset_id'), 'changeset_comments', ['changeset_id'], unique=False)
    op.create_table('changeset_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('changeset_id', sa.BigInteger(), nullable=True),
    sa.Column('k', sa.String(), nullable=False),
    sa.Column('v', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['changeset_id'], ['changesets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changeset_tags_changeset_id'), 'changeset_tags', ['changeset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_changeset_tags_changeset_id'), table_name='changeset_tags')
    op.drop_table('changeset_tags')
    op.drop_index(op.f('ix_changeset_comments_changeset_id'), table_name='changeset_comments')
    op.drop_table('changeset_comments')
    op.drop_table('metadata')
    op.drop_index('idx_changesets_user_created_at', table_name='changesets')
    op.drop_index('idx_changesets_user', table_name='changesets')
    op.drop_index('idx_changesets_num_changes', table_name='changesets')
    op.drop_index('idx_changesets_created_at', table_name='changesets')
    op.drop_index('idx_changesets_comments_count', table_name='changesets')
    op.drop_geospatial_index('idx_changesets_bbox_geom', table_name='changesets', postgresql_using='gist', column_name='bbox')
    op.drop_index('idx_changesets_bbox', table_name='changesets')
    op.drop_geospatial_table('changesets')
    # ### end Alembic commands ###
