"""initial migration

Revision ID: 615da3f69d1d
Revises: 
Create Date: 2025-02-07 20:38:58.087692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '615da3f69d1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
